import 'styles/globals.css';

interface ILayout {
  children: React.ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const layout: React.FC<ILayout> = ({ children }) => {
  return (
    <html lang="en">
      <main className="main">{children}</main>
    </html>
  );
};

export default layout;
